### ISSUE TITLE
Question: Are these components compatible with React Native?

### ISSUE THREAD

**Issue by janvarsa** [vasturiano/react-force-graph#225]

**Comment by mbonig** [comment]
Not sure if it helps, but it doesn't appear to work for me. I'm using the iOS Simulator and expo and I get nothing out of the app. It appears to be a failure but I can't see why.

**Comment by ohmygaugh-crypto** [comment]
Expo Web Browser works for me, but I too haven't succeeded in getting this to run on a mobile emulator(Android). _I get this error when trying to run on the Android emulator:_ 
![image](https://user-images.githubusercontent.com/58447309/120108333-b38fbf80-c132-11eb-9b91-424156ae409a.png)

Error: While trying to resolve module `bezier-js` from file `C:\Users\Seth\PROJECTS\graphui\reactnative\b\node_modules\force-graph\dist\force-graph.common.js`, the package `C:\Users\Seth\PROJECTS\graphui\reactnative\b\node_modules\bezier-js\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\Users\Seth\PROJECTS\graphui\reactnative\b\node_modules\bezier-js\dist\bezier.cjs`. Indeed, none of these files exist:

  * C:\Users\Seth\PROJECTS\graphui\reactnative\b\node_modules\bezier-js\dist\bezier.cjs(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.json|.native.json|.json)
  * C:\Users\Seth\PROJECTS\graphui\reactnative\b\node_modules\bezier-js\dist\bezier.cjs\index(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.json|.native.json|.json)
    at DependencyGraph.resolveDependency (C:\Users\Seth\PROJECTS\graphui\reactnative\b\node_modules\metro\src\node-haste\DependencyGraph.js:376:17)
    at Object.resolve (C:\Users\Seth\PROJECTS\graphui\reactnative\b\node_modules\metro\src\lib\transformHelpers.js:271:42)
    at resolve (C:\Users\Seth\PROJECTS\graphui\reactnative\b\node_modules\metro\src\DeltaBundler\traverseDependencies.js:571:33)
    at C:\Users\Seth\PROJECTS\graphui\reactnative\b\node_modules\metro\src\DeltaBundler\traverseDependencies.js:587:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (C:\Users\Seth\PROJECTS\graphui\reactnative\b\node_modules\metro\src\DeltaBundler\traverseDependencies.js:586:33)
    at C:\Users\Seth\PROJECTS\graphui\reactnative\b\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Seth\PROJECTS\graphui\reactnative\b\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
    at _next (C:\Users\Seth\PROJECTS\graphui\reactnative\b\node_modules\metro\src\DeltaBundler\traverseDependencies.js:107:9)

**Comment by ohmygaugh-crypto** [comment]
https://issueexplorer.com/issue/vasturiano/force-graph/182
