### ISSUE TITLE
Click or grad on canvas on resize throws error 

### ISSUE THREAD

**Issue by sushantone** [vasturiano/react-force-graph#464]
Cannot read properties of undefined (reading 'children')
TypeError: Cannot read properties of undefined (reading 'children')
    at emptyObject (http://localhost:3000/static/js/bundle.js:66465:14)
    at _objectSpread2.objBindAttr (http://localhost:3000/static/js/bundle.js:66483:5)
    at http://localhost:3000/static/js/bundle.js:64418:5
    at Array.forEach (<anonymous>)
    at viewDigest (http://localhost:3000/static/js/bundle.js:64413:8)
    at threeDigest (http://localhost:3000/static/js/bundle.js:66479:64)
    at Function.update (http://localhost:3000/static/js/bundle.js:67272:7)
    at http://localhost:3000/static/js/bundle.js:65040:16
    at invokeFunc (http://localhost:3000/static/js/bundle.js:65476:19)
    at trailingEdge (http://localhost:3000/static/js/bundle.js:65516:14)

![image](https://github.com/vasturiano/react-force-graph/assets/68579650/aba3fa5e-50a0-40d1-898f-7fa05080f9d2)

**Comment by vasturiano** [comment]
@sushantone please create a simple reproducing example at [codesandbox](https://codesandbox.io/) so we can have a closer look.
